---
- hosts: all
  user: "{{ user }}"
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - { role: common }
    - { role: vagrant }
    - { role: docker }
    - { role: zsh }
    - { role: dotfiles }
    - { role: php }
    - { role: nvm }
    - { role: composer }
    - { role: settings-config }

