---
- name: Install PHP 7.0 from apt
  apt: name={{ item }} state=present
  with_items:
    - php7.0
    - php7.0-cli
    - php7.0-curl
    - php7.0-json
    - php7.0-mysql
    - php7.0-sqlite3
    - php7.0-mbstring
    - php7.0-xml

